version: '3'
services:
  mongo:
    build:
      context: ./mongo/
    image: mongo
    hostname: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - game-app

networks:
  game-app:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.101.101.0/24